imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@BlogBundle/Resources/config/config.yml" }
    - { resource: "@AppBundle/Resources/config/config.yml" }
    - { resource: "@BackendBundle/Resources/config/config.yml" }

parameters:
    upload_directory: '%kernel.root_dir%/../web/'
    google_javascript_API: AIzaSyCA3AYDNntCXV9MA5TcrUP1RaFVpfqiU38
    
framework:
    esi:             true
    default_locale:  "es"
    #translator:      
        #fallbacks: ["%locale%"]
        #paths:
        #    - "%kernel.root_dir%/Resources/translations"
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
 
sensio_framework_extra:
    router:
        annotations: false
 
# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:      
        - "form/fields.html.twig"
    globals:
        google_API: "%google_javascript_API%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                dql:
                    datetime_functions:
                        MONTH: DoctrineExtensions\Query\Mysql\Month
                        YEAR: DoctrineExtensions\Query\Mysql\Year

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      25
    encryption: null
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }