imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @BlogBundle/Resources/config/config.yml }
    - { resource: @AppBundle/Resources/config/config.yml }
    
framework:
    esi:             true
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "es"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: true
    bundles:        [AppBundle]
    filters:
        cssrewrite: ~
        sass: ~
        jpegoptim:
            bin: "%kernel.root_dir%/Resources/jpegoptim/jpegoptim.exe"
            max: 60
            apply_to: "\.jpg$"
        uglifyjs2:
            bin: "%kernel.root_dir%/Resources/uglifyjs/uglifyjs"
        uglifycss:
            bin: "%kernel.root_dir%/Resources/uglifycss/uglifycss"
    twig:
        functions:
            jpegoptim: { output: images-opt/*.jpg }
            
# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                dql:
                    datetime_functions:
                        MONTH: DoctrineExtensions\Query\Mysql\Month
                        YEAR: DoctrineExtensions\Query\Mysql\Year

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      25
    encryption: null
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

doctrine_migrations:
    dir_name: %kernel.root_dir%/DoctrineMigrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations
