main_pages:
    resource: "@MainPagesBundle/Resources/config/routing.yml"
    prefix:   /

budget_calculator:
    resource: "@BudgetCalculatorBundle/Resources/config/routing.yml"
    prefix:   /

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /blog

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
