app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

calculator:
    resource: "@CalculatorBundle/Resources/config/routing.yml"
    prefix:   /

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /blog