# app/config/security.yml
security:
    firewalls:
        backend:
            switch_user: { role: ROLE_ADMIN }
            pattern: ^/*
            anonymous: ~
            provider: users
            form_login:
                login_path: backend_user_login
                check_path: backend_user_login_check
                default_target_path: backend_homepage
            logout:
                path: backend_user_logout
            remember_me:
                secret: '%secret%'
                lifetime: 86400
                path: /
            logout_on_user_change: true
            
    access_control:
        - { path: ^/backend/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/user/*, roles: ROLE_ADMIN }
        - { path: ^/backend/users, roles: ROLE_ADMIN }
        - { path: ^/enquiry/remove/*, roles: ROLE_ADMIN }
        - { path: ^/backend/*, roles: [ROLE_USER, ROLE_ADMIN] }
            
    providers:
        users:
            entity: { class: BackendBundle\Entity\User, property: username }

    encoders:
        BackendBundle\Entity\User: { algorithm: sha512, iterations: 100}