Main_pages_homepage:
    pattern: /
    defaults: { _controller: MainPagesBundle:Page:home }
    
Main_pages_contact:
    pattern: /contacto
    defaults: { _controller: MainPagesBundle:Page:contact }
    requirements:
    methods:  [POST]

Main_pages_static:
    pattern: /{page}
    defaults: { _controller: MainPagesBundle:Page:static }
    methods:  [GET]