# src/Blogger/BlogBundle/Resources/config/config.yml
parameters:
    # dirección de correo electrónico para contacto del Blogger
    blogger_blog.emails.contact_email: contact@email.com
    # Blogger máximo de comentarios recientes
    blogger_blog.comments.latest_comment_limit: 10