# src/BlogBundle/Resources/config/routing.yml
blog_homepage:
    path: /{page}
    defaults:
        _controller: BlogBundle:Front:index
    requirements:
        methods: GET
        page: \d+

blog_article_show:
    path: /{slug}
    defaults: 
        _controller: BlogBundle:Article:show
        comments: true
    requirements:
       methods: GET

blog_comment_create:
    path: /{slug}/create-comment
    defaults:
        _controller: BlogBundle:Comment:create
    requirements:
        methods: POST
       
blog_catag_show:
    path: /{slug}/{page}
    defaults:  
        _controller: BlogBundle:Catag:show
    requirements:
       methods: GET

        