services:
    blog.twig.extension:
        class: BlogBundle\Twig\Extensions\DateBlogExtension
        tags:
            - { name: twig.extension }
    
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
