app_homepage:
    pattern: /
    defaults: { _controller: AppBundle:Page:inicio }
    
app_contact:
    pattern: /contacto
    defaults: { _controller: AppBundle:Page:contact }
    requirements:
    methods:  [POST]
    
app_sitemap:
    pattern: /sitemap.{_format}
    defaults: { _controller: AppBundle:Sitemap:sitemap , _format: xml }
    requirements: 
        _format : xml

app_project:
    pattern: /proyectos/{project}
    defaults: { _controller: AppBundle:Page:project }
    methods:  [GET]

app_gallery:
    pattern: /proyectos/{project}/{gallery}
    defaults: { _controller: AppBundle:Page:gallery }
    methods:  [GET]

app_static:
    pattern: /{page}
    defaults: { _controller: AppBundle:Page:static }
    methods:  [GET]